### ISSUE TITLE
JSON File Format for Forms

### ISSUE THREAD

**Issue by seveibar** [rpiml/okcollege-web-client#2]

**Comment by seveibar** [comment]
Proposal (I would recommend allowing a yaml'd version too)
```javascript
{
  firstPage: "start",
  pages: [
    {
      "id": "start",
      "questions": [{
        "id": "years-in-college",
        "question": "How many years have you been in college?",
        "type": "slider",
        "range": [0,5]
      }],
      "next": "activites"
    },
    {
      "id": "activities",
      "questions": [{
        "id": "sports",
        "question": "What sports do you play?",
        "type": "multi-choice",
        "hasOther": true,
        "answers": ["Tennis", "Basketball", "Football"]
      },{
        "id": "clubs",
        "question": "What is your favorite club?",
        "type": "choice",
        "answers": ["RSA", "FSAE", "IEEE"]
      }],
      "next": "done"
    }
  ]
}
```

**Comment by seveibar** [comment]
YAML Finalized:
```yaml
---
firstPage: start
pages:
- id: start
  questions:
  - id: years-in-college
    question: How many years have you been in college?
    type: slider
    range:
    - 0
    - 5
  next: activites
- id: activities
  questions:
  - id: sports
    question: What sports do you play?
    type: multi-choice
    hasOther: true
    answers:
    - Tennis
    - Basketball
    - Football
  - id: clubs
    question: What is your favorite club?
    type: choice
    answers:
    - RSA
    - FSAE
    - IEEE
  next: done
```

JSON Finalized
```javascript
{
  "firstPage": "start",
  "pages": [{
      "id": "start",
      "questions": [{
        "id": "years-in-college",
        "question": "How many years have you been in college?",
        "type": "slider",
        "range": [0,5]
      }],
      "next": "activites"
    },
    {
      "id": "activities",
      "questions": [{
        "id": "sports",
        "question": "What sports do you play?",
        "type": "multi-choice",
        "hasOther": true,
        "answers": ["Tennis", "Basketball", "Football"]
      },{
        "id": "clubs",
        "question": "What is your favorite club?",
        "type": "choice",
        "answers": ["RSA", "FSAE", "IEEE"]
      }],
      "next": "done"
    }
  ]
}

```
